name = "amurta-hospital"
type = "javascript"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[env.production]
name = "amurta-hospital-prod"

